#!/bin/sh

barsep="]["

getdate()
{
  echo $(date +"%a, %b %d - %I:%M")
}

getpackages()
{
  # Arch
  #echo "Packages: $(pacman -Q | wc -l)"
  # Gentoo
  #echo "Packages: $(ls -d /var/db/pkg/*/* | wc -l)"
  # Void
  echo "Packages: $(xbps-query -l | wc -l)"
}

getvolume()
{
  echo "Volume: $(amixer get Master | awk 'FNR == 5 {print $4}' | tr -d "[]")"
}

getpower()
{
  power=$(cat /sys/class/power_supply/BAT0/capacity)
  charging=$(cat /sys/class/power_supply/BAT0/status)
  if [ $charging = 'Charging' ]; then
    charge='^'
  else
    charge=''
  fi
  echo "Battery: $power$charge"
}

hddspace()
{
  echo "Free space: $(df -h | grep /dev/sda4 | awk '{print $4}')"
}

while true; do
  xsetroot -name "[$(getpackages)$barsep$(hddspace)$barsep$(getpower)$barsep$(getvolume)$barsep$(getdate)]"
  sleep 10s
done &
